.TH PMCPUTEMP 1 "20 September 2014"
.SH NAME
pmcputemp \- a poor man's cpu temperature status icon
.SH SYNOPSIS
\fBpmcputemp\fP
.SH DESCRIPTION
\fBpmcputemp\fP displays a an icon in the system tray
displaying the current CPU temperature, updated every 5 seconds.
.SS Options
.TP
[integer] 1 to 10. This overrides the default 5 second delay
.TP
Right clicking presents a small menu to display "About" dialog or "Quit",
which terminates the application.
.TP
It can only be invoked from CLI or script. It can be autostarted with a 
window manager. See your distribution's documentation for this feature.
.TP
At first run, a script attempts to identify the correct file on your
system which is sourced to generate the temperature in degrees Celcius.
If a sensor module is not loaded it does attempt to do this.
.SH FILES
.TP
\fI/usr/bin/pmcputemp\fR
.TP
\fI/usr/bin/pmcputemp.sh\fR
.SH "SEE ALSO"
sensors(1)
.SH BUGS
.TP
Fahrenheit is unsupported.
.TP
The script may not find your temperature file.
.SH "AUTHOR"
.IX Header "AUTHOR"
Michael Amadio - 01micko@gmail.com
.SH "COPYRIGHT AND LICENSE"
.IX Header "COPYRIGHT AND LICENSE"
\&\fBCopyright (C)\fR 2014 by Author.  
.PP
\&\fBpmcputemp\fR is free software; you can redistribute it and/or modify it
under the terms of the \s-1GPL-v2.0\s0.
